server:
  port: 8087

spring:
  application:
    name: profile
  datasource:
    username: 'educamer'
    url: jdbc:postgresql://172.18.0.3:5432/profile
    password: 'password'
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: update
      show-sql: 'true'
