server:
  port: 8087

spring:
  application:
    name: profile
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/profile
    password: 'admin'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
